### ISSUE TITLE
大佬有epub的版本吗？方便在kindle上阅读。

### ISSUE THREAD

**Issue by puppetmonkey** [berryjam/mastering-bitcoin-3rd#2]

**Comment by berryjam** [comment]
目前尝试了好多方式暂时还不能导出pdf，如果能的话，应该可以用calibre转epub，继续尝试下。

**Comment by berryjam** [comment]
> _No description provided._


目前尝试了好多方式暂时还不能导出pdf，如果能的话，应该可以用calibre转epub，继续尝试下。

**Comment by berryjam** [comment]
> _No description provided._

经过一番研究，使用[honkit](https://github.com/honkit/honkit)分别成功导出pdf、epub，欢迎下载查看。

pdf下载链接：https://berryjam.github.io/mastering-bitcoin-3rd/book.pdf
epub下载链接：https://berryjam.github.io/mastering-bitcoin-3rd/book.epub

**Comment by puppetmonkey** [comment]
谢谢大佬。
