### ISSUE TITLE
请问电子书和实体书内容上有区别吗？

### ISSUE THREAD

**Issue by xiaobinqt** [berryjam/mastering-bitcoin-3rd#4]
您好，请问电子书和实体书内容上有区别吗？

**Comment by berryjam** [comment]
> 您好，请问电子书和实体书内容上有区别吗？

您好，网页版的是在实体书的基础上，添加了3个实战的知识点：
1.比特币java应用开发示例
2.rust的brc20编程实践
3.BTC二层详细技术分析
其余内容基本一致。
