### ISSUE TITLE
翻译的一些准确性的问题

### ISSUE THREAD

**Issue by shawn246** [berryjam/mastering-bitcoin-3rd#6]
首先对作者的翻译工作表示敬佩。阅读过程中对一些句子的意思产生了疑惑，所以去查找了原文，例如
截取chapter 2 -> Bitcoin Mining中的一段：
原文：Miners can only receive honest income from creating blocks that follow all of Bitcoin’s consensus rules.
译文：矿工只能从符合所有比特币共识规则的区块中获得诚实的收入。
译文把原文中creating的意思给漏了，造成译文的意思有点模糊不清了。

我觉得用google translate或者gpt作为基础翻译，再加上人工的审核可能能较大概率的避免这类问题，当然这个工作量也不小。还是感谢作者的译文，继续对照着看：）

**Comment by berryjam** [comment]
> 首先对作者的翻译工作表示敬佩。阅读过程中对一些句子的意思产生了疑惑，所以去查找了原文，例如 截取chapter 2 -> Bitcoin Mining中的一段： 原文：Miners can only receive honest income from creating blocks that follow all of Bitcoin’s consensus rules. 译文：矿工只能从符合所有比特币共识规则的区块中获得诚实的收入。 译文把原文中creating的意思给漏了，造成译文的意思有点模糊不清了。
> 
> 我觉得用google translate或者gpt作为基础翻译，再加上人工的审核可能能较大概率的避免这类问题，当然这个工作量也不小。还是感谢作者的译文，继续对照着看：）

你说的没错，后面我也会抽空再人工审核下。对于比较明显的，可以提出pr 修正哈，因为初心就是希望与大家一起来完善，带给大家更新的还有实践的比特币学习资料。
